### ISSUE TITLE
Expose Track.getClipSlots()

### ISSUE THREAD

**Issue by giohappy** [ricardomatias/ableton-live#10]
I find myself doing `track.children("clip_slots")` to obtain the full list of clip slots, including the empty ones.
What about exposing a `Track.getClipSlots()` method? Maybe in the `wip` branch, where I see you're adding new useful things.

**Comment by ricardomatias** [comment]
Do you have in mind additional/different behavior to `track.children("clip_slots")`?

**Comment by giohappy** [comment]
On second thought, I suppose methods are only used to extract/transform properties.In that case I think it's just fine to use `track.children("clip_slots")` and you can close this.
