### ISSUE TITLE
would you be able a way to observe the start of a clip playing?

### ISSUE THREAD

**Issue by lidoravitan** [ricardomatias/ableton-live#13]
I want to do something immediately when some clip started to play.
would you be able a way to observe the start of a clip playing?

i tried to use 'play_position' but it starts little bit after 0ms

**Comment by ricardomatias** [comment]
Sorry for the late reply @lidoravitan. Did you manage to figure out a way to do this? If you know when the clip will start playing, listen to an earlier play_.position, f.ex: clip fires at 4:0:0, you should listen to 3:4:4 (f.ex).

**Comment by ricardomatias** [comment]
Closed for lack of updates
