### ISSUE TITLE
Possible documentation and/or LiveAPI.amxd issue

### ISSUE THREAD

**Issue by bendorge** [ricardomatias/ableton-live#15]
Hi there,

Great library! I think I'm missing something trivial here, but I found a few issues with the Read ME page and possibly the LiveAPI.amxd file as well. 

I tried the 3 simple steps mentioned with Ableton running, but the very first connection is refused followed by the timeout after the default 20 attempts. No other apps are using the port from what I can tell. 

Clicking the arrow button on the plugin in Ableton seems to turn green, but that's it. The colour toggles back immediately after switching back to the console. 

Clicking Restart on the plugin crashes Ableton. 

Any ideas on what I'm missing to create a successful connection? I used the example code as written in the READ ME.

**Comment by ricardomatias** [comment]
Hello @bendorge, could you make sure that the device is using port 9001 and in code, instantiate AbletonLive like this `const live = new AbletonLive({ port: 9001, logRequests: true });`. Please also update to 0.0.7 that was just released.

**Comment by ricardomatias** [comment]
Closing this for now, please reopen if it's still relevant to you.
