### ISSUE TITLE
is it possible to create a clip envelope? 

### ISSUE THREAD

**Issue by marisademeglio** [ricardomatias/ableton-live#21]
Thanks for this library, I've had some fun using it! What I'm wondering is can I use it to assign an envelope to a clip - for example, I would like to create a panning envelope programmatically.

**Comment by ricardomatias** [comment]
Hello @marisademeglio, sorry for the late reply. I guess you've probably figured this out, but according to the LOM (Live Object Model), there is not way to programmatically create envelopes (automation).
