### ISSUE TITLE
Issues with Ableton 11.3.20

### ISSUE THREAD

**Issue by f-f** [ricardomatias/ableton-live#24]
Hi - I was happily using this on Ableton 11.3.13, but it seems to have stopped working now that I am on version 11.3.20 (I double checked this on a different machine that was running .13, and later upgraded that one to .20 as well, and I replicated the failure)

The error I'm getting is that `track.volume()` crashes with `TypeError: Cannot read properties of undefined (reading 'id')`, but that seems a symptom of overall funkiness: all `track.id` and `track.name` are `0`, and `live.song.children("track")` only returns midi tracks.

So something is quite off somewhere - I went looking for [the changelog](https://www.ableton.com/en/release-notes/live-11/), and the most relevant change seems to be the ["Updated the bundled Max build to version 8.5.6"](https://cycling74.com/releases/max/8.5.6), so maybe something in Max changed?

I know nothing about Max so I am not sure where to look for more info on how to debug this, but I'm happy to assist.

**Comment by f-f** [comment]
Hm, I get this even after I downgraded to 11.3.13, so maybe something gets set in the project?

**Comment by f-f** [comment]
I found the Max editor and got some logs, it doesn't seem very happy:
<img width="573" alt="image" src="https://github.com/ricardomatias/ableton-live/assets/5480361/7c46cf34-a40f-4d85-a51d-3e331ae441bd">

**Comment by f-f** [comment]
Hmm, I tried to verify things worked on an entirely different machine running 11.2, and it still fails in the same way, so I am pretty puzzled right now. This is using Node 18.18.2.

**Comment by ricardomatias** [comment]
Hey @f-f, I didn't have time till now to look at it. I'm reopening this to use as the base issue for the problem since it has relevant information.

**Comment by f-f** [comment]
No worries @ricardomatias, we all busy 😄 I was just in a hurry because I have a performance in a few days and I _needed_ my setup to work, and it seemed irrimediably broken after the update (i.e. even downgrading didn't fix it), so I switched to [this thing in the meantime](https://github.com/ideoforms/AbletonOSC) (which I'm now happy about because I don't know enough Max to properly debug things in haste) - all of this to say that I won't need the fix myself anymore

**Comment by ricardomatias** [comment]
@f-f I understand your situation.

Bug is fixed with 0.0.11 release.

**Comment by f-f** [comment]
Is that pushed? I don't see it on the repo page

**Comment by f-f** [comment]
Lovely, JS' `null` vs `undefined` bites once more 🙂
