### ISSUE TITLE
Read info_text from a Clip

### ISSUE THREAD

**Issue by celestial-labs** [ricardomatias/ableton-live#26]
I'm currently using the ableton-live npm package to interact with Ableton Live, and I'm trying to read the info_text property from a Clip object. I couldn't find any direct method or property in the documentation or the codebase that allows access to the info_text of a Clip.

**Expected Behavior:**
I expect to retrieve the info_text of the specified Clip.

**Actual Behavior:**
An error is thrown because the info_text property does not seem to exist on the Clip object.

**Comment by ricardomatias** [comment]
According to the [Live Object Model](https://docs.cycling74.com/max8/vignettes/live_object_model) this property isn't exposed by the Max4Live API.
