### ISSUE TITLE
Get Cue_Points Name?

### ISSUE THREAD

**Issue by Sim0n18** [ricardomatias/ableton-live#28]
Hi,

i hope this is the right place to ask this. I am using this package for the first time and really like it and also the documentation.
In the documentation i just found out how to get the count and id with the path of the cue points but i would also like to get the name of them like they are called in ableton. Based on the package abletonJS there is a "name" string type on the cue_points which is what i am looking for.
Is there a way to do it or implement it? I think this would help a lot of people using it, especially for live sets.

Thank you very much and i appreciate your work!
Greetings Simon

**Comment by ricardomatias** [comment]
Hello @Sim0n18, I've started working on this but there were some issues that came up. I'll try to find sometime in the near future to submit this. As always, feel free to submit a PR if you manage to implement this

**Comment by Sim0n18** [comment]
Hi @ricardomatias, I would love to contribute, but as this is my first time contributing to open-source, i may ask, how to get the code up and running once forked, so i can test my changes? Could you maybe help me out with this one?

**Comment by ricardomatias** [comment]
@Sim0n18 I've released a new version that adds the cue points functionality need to get and set them.

Regarding local development, I'll add some documentation in the future about it.
