### ISSUE TITLE
Send close frame to clients when server is closed

### ISSUE THREAD

**Issue by giohappy** [ricardomatias/ableton-live#9]
I want my client to be notified when the server is closed (port changed). I was able to get the expected message by calling ws.end() on each client after [this line](https://github.com/ricardomatias/ableton-live/blob/f8d504e597738f569746c5dbc5ca3046f6473da4/external/LiveAPI/node-content/node-live-api.js#L27):

```javascript
maxApi.addHandler('port', async (port) => {
	try {
		if (uws) {
			console.log('Attempting to close server..');

			if (listenSocket) uWS.us_listen_socket_close(listenSocket);
			
			SOCKETS.forEach((ws, i) => ws.end());
		}

		console.log('Creating server..');
		
		....
```

As uWebSockets [explains](https://github.com/uNetworking/uWebSockets/blob/021dfe19374065f615d49be5d8f30b7cce836a9d/src/WebSocket.h#L163), ws.end() does:

>Send websocket close frame, emit close event, send FIN if successful. Will not append a close reason if code is 0 or 1005.

**Comment by giohappy** [comment]
I can wait for the merge of the wip branch. Do you know more or less when it will happen?

**Comment by ricardomatias** [comment]
Sorry for the long delay @giohappy. There have been a few updates to the project this past week and I'm now returning to this issue. Did you get to try the "wip" branch?

**Comment by giohappy** [comment]
@ricardomatias unfortunately I hade to pause my side project where I was using your code. I hope I will be back on it sooner then later, but there"s a good chance it will be with a Python client.

**Comment by ricardomatias** [comment]
Part of the latest release of v0.0.10
